version: '3.8'

services:
  # --- PRESENTATION TIER (FRONTEND) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nutritrack-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # --- LOGIC TIER (BACKEND) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutritrack-backend
    environment:
      - FLASK_APP=app.main
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://nutri_admin:nutri_password@database:5432/nutritrack_db
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy  # <--- Wait until the database health check passes completely

  # --- DATA TIER (DATABASE) ---
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: nutritrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nutritrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutri_admin -d nutritrack_db"]
      interval: 3s
      timeout: 3s
      retries: 5

 # --- AUTOMATION SERVER (CI/CD) ---
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: nutritrack-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # --- ADD THESE TWO LINES TO SHARE YOUR HOST'S DOCKER CLI ENGINE PERMANENTLY ---
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/local/lib/docker/cli-plugins/docker-compose

# ==============================
# GLOBAL VOLUMES CONFIGURATION 
# ==============================
volumes:
  postgres_data:
  jenkins_data: